### ISSUE TITLE
Polkadot contract wizard roadmap

### ISSUE THREAD

**Issue by alongoni** [alongoni/polkadot-contract-wizard#1]
**Tasks**

- [x] 1.- Develop mockup of the frontend interface

- The development need to be focused on UX
- There’s already a tool we can base our work on: https://wizard.openzeppelin.com/
- Think the user can be an artist that need to create a new NFT token contract for publishing their own content
- Think the user is a non technical person that has a great idea and need to create a new PSP22 for being able to finance it’s own project.

- [x] 2.- Develop interface with no functionality

- Based on the mockup created in the previous step make it something usable
- Need to be very careful about the Look and Feel
- Don't forget the UX approach.

- [x] 3.- Add syntax highlighting to the code in rust for PSP22 at the beginning

- We need to find a library that covers not only Rust language, but let’s have in mind Assembly Script will be required in the future, or any other language that has a transpiler and could be compatible with wasm.
- Copy the PSP22 contracts from here: https://github.com/Supercolony-net/openbrush-contracts/blob/main/contracts/src/token/psp22/psp22.rs

- [ ] 4.- Compose the contracts based on the selection

- All Rust contracts need to be composables based on the modifiers selected by the user. 
- The rs code of the modifiers is already here: https://github.com/Supercolony-net/openbrush-contracts/tree/main/contracts/src/token/psp22/extensions

- [x] 5.- Add copy button the ability to copy the code generated

- Check the copied code is exactly the same as the generated code

- [ ] 6.- Add download button the ability to generate the file and download it

- Check the downloaded file contains exactly what was generated in the UI

- [ ] 7.- Add PSP34 functionality.

- Include the PSP34 functionality 
- Base code and the extensions are already here: https://github.com/Supercolony-net/openbrush-contracts/tree/main/contracts/src/token/psp34

- [ ]  8.- Develop Add/Instance functionality, hardcoded to Canvas parachain in Rococo PSP22 base

- At the very beginning we will need to deploy an instance in the same step. Even if the same contract was already created in the parachain.
- Check documentation here: https://github.com/paritytech/canvas
- The compiled file to upload will be the PSP22 base, nevermind the selection and can be hardcoded.

- [ ] 9.- Compile code generated and deploy it Canvas parachain in Rococo

- We will need to find a compiler to integrate in the UI for compiling the code that’s displayed in the interface.
- Integrate the compiler to the UI, creating the compiled file and uploading it to create an instance of the contract.

- [ ] 10.- Store a map containing addresses of contracts already deployed on each parachain for creating instances when possible

- We need a map containing parachain (WS or name), type of the contract (PSP22 - base /  PSP22- burnable / <And so on>) and the address already deployed. 
- Research what’s the best place to store this and what’s the most efficient way.

- [ ]  11.- Add create instances when possible of already deployed contracts

- Based on previous research implement the create instance instead of deploying every time

- [ ]  12.- Create functionality to deploy on custom parachain adding WS information

- Add the ability to select which parachain you want to deploy, show errors if fail to deploy or connect.

- [ ] 13.- Develop standard contracts with modifiers using ASK

- Based on what’s already implemented in INK, create the same contracts using ASK. (the idea behind that is to promote ASK as an alternative to INK)

- [ ] 14.- Integrate ASK functionality with ASK button.

- Integrate previous contracts in the ask button.

- [ ]  15.- Check and test download and copy button is copying from ASK

- Check everything is working as expected.

- [ ]  16.- Solve compiling ASK in the front end with the code generated

- As it was solved on point 9 let’s find a way to do the same using ASK.

- [ ] 17.- Make the code deployable with changes made in the code for INK and ASK.

- Be able to deploy code compiled with INK and ASK

- [ ] 18.- Add the ability of creating custom contracts, not only with the modifiers but adding the ability to write code using the interface.

- At this point we need to be able to make changes in the code and be able to compile that code. 
- Add a warning if you want to change language from INK to ASK and vice-versa saying if you change language all custom changes will be lost.

- [ ] 19.- Create a social network ability by creating a user based on your github account.

- Link to github using its api for making the user able to log in.

- [ ] 20.- Add the ability to directly create the project on the users github account.

- Add a create github project button.
- It should contain a minimum README.md containing something saying it was built on this tool

- [ ] 21.- Create a github project based on the changes made in the UI

- Include code tabs for automatically generating a README.md file template.

- [ ] 22.- Add a selector on deploying for choosing the license of the publication

- Add default MIT license but generate the ability for being able to change it by the most common ones

- [ ] 23.- Add workspaces

- Create a drop down selector for naming the current workspace.
- Workspace will include all options selected and the code the user is able to compile.

- [ ] 24.- Add an option for sharing the workspace with an existing user.

- We need to make it possible to share the users workspace with a github friend. A Github friend will be able to open that code on his own account and create his own workspace based on it.
- Workspaces are not common documents, a snapshot (commit) is shared with the user.

- [ ] 25.- Create a telegram community for developers to support the usage of the tool

- With help from community builders and ambassadors we can create a telegram for helping the community in the usage of the tool.

- [ ] 26.- Create video tutorials about how to use it in INK and ASK (Epic)

- [ ] 27.- Explore small tweaks to the code and create custom contracts in both languages showing the community how easy it is to change a contract and share it with a friend. (Tutorial)

- [ ] 28.- Based on the community needs, add new standards to the tool.

- Explore adding new extensions
- Explore adding new PSP contracts

- [ ] 29.- Explore possibilities of transpiling code from INK to ASK and vice-versa for being able to change windows without losing the changes already made. (see point 18)

_Solang is in the development phase. Once this is reliable enough include it in the menu._
